### PR TITLE
lots o upgrades

### PR DESCRIPTION
**Pull request by adangert**
added sound fx, fixed tie bug, increased sensitivity threshold from 60 to 40, added introductory instructions before level 4, added gallery unlock

### CODE REVIEW

**Comment by AEFeinstein** [comment]
Bug report. If you connect two Swadges, then turn one off, the one that is on gets stuck playing Joust. There's no heartbeat message during gameplay, so it never knows the other disappears. If it shakes and tries to send the 'I lost' message, `joustMsgTxCbFn()` is called with `MSG_FAILED`, but nothing happens.

At a minimum, the game should abort and go back to the menu if `MSG_FAILED` happens. Even better would be a heartbeat message sent every few seconds, and if three heartbeats are missed in a row, then the game aborts back to the menu.

**Comment by AEFeinstein** [comment]
I'd recommend having a third SFX for tie, rather than reusing the one for win

**Comment by adangert** [comment]
I haven't actually been able to trigger a tie game after the newest changes, it might be impossible potentially.

**Comment by AEFeinstein** [comment]
I got a tie, that works as expected :)

**Pull request merged**
